# Generated by Django 5.1.15 on 2026-08-26 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('trigger', models.CharField(choices=[('Welcome', 'A new customer'), ('WinBack', 'A customer who has gone quiet'), ('PostPurchase', 'After an order'), ('AbandonedCart', 'A basket left behind')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=8000)),
                ('delay_hours', models.PositiveIntegerField(default=24)),
                ('segment_slug', models.SlugField(blank=True, default='', max_length=150)),
                ('maximum_per_run', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knight_marketing_campaign',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('Unsubscribed', 'Asked not to be mailed'), ('Bounced', 'The address does not accept mail'), ('Complained', 'Reported as spam'), ('Manual', 'Suppressed by staff')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'knight_marketing_suppression',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('consented_at', models.DateTimeField()),
                ('locale', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knight_marketing_contact',
                'ordering': ('subject',),
                'indexes': [models.Index(fields=['email'], name='knight_mkt_contact_email')],
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ref', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('state', models.CharField(choices=[('Pending', 'Not yet attempted'), ('Sent', 'Handed to the provider'), ('Failed', 'The provider refused it'), ('Suppressed', 'Not sent: the recipient must not be mailed'), ('NoContact', 'Not sent: no consented address')], default='Pending', max_length=16)),
                ('subject_line', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=250)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='knight_marketing.campaign')),
            ],
            options={
                'db_table': 'knight_marketing_send',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['campaign', 'state'], name='knight_mkt_send_state'), models.Index(fields=['subject_ref'], name='knight_mkt_send_subject')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'subject_ref'), name='knight_marketing_once_per_campaign_and_subject')],
            },
        ),
    ]
