---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart knight-api
  ansible.builtin.systemd:
    name: knight-api
    state: restarted

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
