# Generated by Django 5.1.15 on 2026-08-25 07:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('rule', models.CharField(choices=[('New', 'New customers'), ('Frequent', 'Frequent customers'), ('HighValue', 'High-value customers'), ('VIP', 'VIP customers'), ('Dormant', 'Dormant customers')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused')], default='Active', max_length=16)),
                ('window_days', models.PositiveIntegerField(default=90)),
                ('minimum_events', models.PositiveIntegerField(default=2)),
                ('minimum_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('dormant_after_days', models.PositiveIntegerField(default=60)),
                ('new_within_days', models.PositiveIntegerField(default=30)),
                ('event_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knight_segment',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('events', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='knight_segments.segment')),
            ],
            options={
                'db_table': 'knight_segment_membership',
                'ordering': ('-total_value', 'subject'),
                'indexes': [models.Index(fields=['segment', '-total_value'], name='knight_seg_mem_value_idx')],
                'constraints': [models.UniqueConstraint(fields=('segment', 'subject'), name='knight_segment_one_row_per_subject')],
            },
        ),
    ]
