# Generated by Django 5.1.15 on 2026-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knight_drill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillrecord',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
