# Generated by Django 5.1.15 on 2026-08-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Everything this Feature owns.

    Three constraints below are the Feature rather than decoration.

    `knight_mkt_one_message_per_external_id` is what makes a partner's redelivery
    free: unique on *their* event id, among the messages that have one. Partial
    because an outbound message has no counterpart id and a blank string would
    collide with every other blank string - which is also why this Feature
    requires PostgreSQL.

    `knight_mkt_one_remote_per_local` and `knight_mkt_one_local_per_remote` are a
    pair on purpose. One of ours maps to one of theirs *and* one of theirs maps
    back to one of ours: without the second, two products both claiming the same
    marketplace listing is a bug that surfaces as a stock level oscillating and
    takes a day to find.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('marketplace', 'A delivery or listing marketplace'), ('pos', 'A point-of-sale system'), ('accounting', 'An accounting or bookkeeping system')], max_length=20)),
                ('adapter', models.CharField(max_length=40)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(choices=[('connected', 'Working'), ('expired', 'The credential needs refreshing'), ('revoked', 'The other end withdrew access'), ('disconnected', 'Switched off here')], default='disconnected', max_length=20)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, default='', max_length=500)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knight_marketplaces_connection',
                'ordering': ('slug',),
                'indexes': [models.Index(fields=['kind', 'state'], name='knight_mkt_conn_kind')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'A product or variant'), ('order', 'An order'), ('customer', 'A customer')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checked', models.PositiveIntegerField(default=0)),
                ('differing', models.PositiveIntegerField(default=0)),
                ('failure', models.CharField(blank=True, default='', max_length=500)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='knight_marketplaces.connection')),
            ],
            options={
                'db_table': 'knight_marketplaces_reconciliation',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('missing-there', 'We have it and they do not'), ('missing-here', 'They have it and we do not'), ('different', 'Both have it and they disagree')], max_length=20)),
                ('local_reference', models.CharField(blank=True, default='', max_length=200)),
                ('remote_id', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='knight_marketplaces.reconciliationrun')),
            ],
            options={
                'db_table': 'knight_marketplaces_difference',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RemoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'A product or variant'), ('order', 'An order'), ('customer', 'A customer')], max_length=20)),
                ('local_reference', models.CharField(max_length=200)),
                ('remote_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='knight_marketplaces.connection')),
            ],
            options={
                'db_table': 'knight_marketplaces_link',
                'ordering': ('connection', 'kind', 'local_reference'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'From them to us'), ('outbound', 'From us to them')], max_length=10)),
                ('kind', models.CharField(max_length=80)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('subject_type', models.CharField(blank=True, default='', max_length=40)),
                ('subject_id', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Waiting to be handled'), ('sent', 'Delivered to them'), ('processed', 'Taken in from them'), ('failed', 'Will be tried again'), ('abandoned', 'Out of attempts, waiting for a person'), ('discarded', 'Deliberately not handled')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('remote_reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knight_marketplaces.connection')),
            ],
            options={
                'db_table': 'knight_marketplaces_message',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='knight_mkt_msg_due'), models.Index(fields=['connection', 'direction', 'state'], name='knight_mkt_msg_queue'), models.Index(fields=['subject_type', 'subject_id'], name='knight_mkt_msg_subject')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('connection', 'external_id'), name='knight_mkt_one_message_per_external_id')],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['connection', '-started_at'], name='knight_mkt_recon_recent'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['run', 'kind'], name='knight_mkt_diff_run'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['resolved_at'], name='knight_mkt_diff_open'),
        ),
        migrations.AddConstraint(
            model_name='remotelink',
            constraint=models.UniqueConstraint(fields=('connection', 'kind', 'local_reference'), name='knight_mkt_one_remote_per_local'),
        ),
        migrations.AddConstraint(
            model_name='remotelink',
            constraint=models.UniqueConstraint(fields=('connection', 'kind', 'remote_id'), name='knight_mkt_one_local_per_remote'),
        ),
    ]
