"""
One definition of what a slug is.

Kept in a single place so category and product can never drift into two
different ideas of "the same slug". The uniqueness constraints are declared on
the normalised value, which makes this function the constraint rather than a
convenience beside it — two names that normalise identically are the same slug,
and the database says so.

Ported from `Catalog.Domain.SlugNormalizer`, deliberately unchanged in
behaviour: existing catalogues have slugs generated by it, and a port that
normalised differently would silently make previously distinct products collide,
or previously identical ones diverge.
"""

from django.core.exceptions import ValidationError

MAX_LENGTH = 150


def normalize(value: str | None) -> str:
    """
    Reduces a name to a slug: lowercase ASCII letters and digits, single hyphens
    between runs of anything else, no leading or trailing hyphen.

    Raises when nothing usable survives, rather than returning an empty string.
    A blank slug would be accepted by the column and then collide with every
    other blank one, which is a uniqueness violation arriving hours later and
    nowhere near its cause.
    """
    if value is None or not value.strip():
        raise ValidationError("Slug is required.")

    characters: list[str] = []

    for character in value.strip().lower():
        if character.isascii() and (character.isalpha() or character.isdigit()):
            characters.append(character)
        elif characters and characters[-1] != "-":
            characters.append("-")

    normalized = "".join(characters).strip("-")

    if not normalized:
        raise ValidationError("Slug must contain at least one letter or digit.")

    if len(normalized) > MAX_LENGTH:
        normalized = normalized[:MAX_LENGTH].strip("-")

    if not normalized:
        raise ValidationError("Slug must contain at least one letter or digit.")

    return normalized
