# Generated by Django 5.1.15 on 2026-08-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OrderConfirmation', 'Order confirmation'), ('PaymentConfirmation', 'Payment confirmation'), ('OrderCancelled', 'Order cancelled'), ('OrderFulfilled', 'Order fulfilled'), ('PasswordReset', 'Password reset')], max_length=32)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=16)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('source_order_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_37b3f3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_order_id__isnull', False)), fields=('kind', 'source_order_id'), name='notification_once_per_order_and_kind')],
            },
        ),
    ]
