# Generated by Django 5.1.15 on 2026-08-27 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Everything this Feature owns, and nothing it does not.

    No `CREATE EXTENSION` here, unlike `advanced-inventory` and
    `advanced-search`: nothing in this package is matched fuzzily, so there is no
    trigram index to support and no shared extension to reason about
    (docs/adr/0031-database-extensions-are-declared-not-migrated.md).

    Three of the constraints below are the Feature rather than decoration.
    `knight_rest_one_open_session_per_table` is a partial unique index, and it is
    what stops two parties' food arriving on one bill. The unique index on a
    slot's start is what stops two overlapping windows each believing they have
    the whole kitchen. And `knight_rest_one_live_ticket_per_number` is partial
    for a reason worth reading twice: ticket numbers roll over at four digits so
    they stay short enough to shout, which means they come round again - two
    tickets a month apart may share one, and two on the board at once may not.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('is_open', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'knight_restaurant_area',
                'ordering': ('display_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='TicketNumberSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_value', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'knight_restaurant_ticket_sequence',
            },
        ),
        migrations.CreateModel(
            name='CapacitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('minutes', models.PositiveSmallIntegerField(default=15)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('service', models.CharField(choices=[('dine-in', 'Eaten here'), ('collection', 'Collected'), ('delivery', 'Delivered')], default='collection', max_length=20)),
                ('capacity_units', models.PositiveIntegerField(default=20)),
                ('is_open', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knight_restaurant_slot',
                'ordering': ('starts_at',),
                'indexes': [models.Index(fields=['location', 'starts_at'], name='knight_rest_slot_when')],
                'constraints': [models.UniqueConstraint(fields=('location', 'service', 'starts_at'), name='knight_rest_one_slot_per_start'), models.CheckConstraint(condition=models.Q(('minutes__gt', 0)), name='knight_rest_slot_has_length')],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('throughput_units_per_hour', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'knight_restaurant_station',
                'ordering': ('display_order', 'code'),
                'constraints': [models.CheckConstraint(condition=models.Q(('throughput_units_per_hour__gt', 0)), name='knight_rest_station_has_throughput')],
            },
        ),
        migrations.CreateModel(
            name='PrepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('object_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('prep_minutes', models.PositiveSmallIntegerField(default=10)),
                ('load_units', models.PositiveSmallIntegerField(default=1)),
                ('is_prepared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='knight_restaurant.station')),
            ],
            options={
                'db_table': 'knight_restaurant_prep_profile',
                'ordering': ('sku',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('seats', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='knight_restaurant.servicearea')),
            ],
            options={
                'db_table': 'knight_restaurant_table',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, default='', max_length=40)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='knight_restaurant.table')),
            ],
            options={
                'db_table': 'knight_restaurant_session',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order_number', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveIntegerField(editable=False)),
                ('service', models.CharField(choices=[('dine-in', 'Eaten here'), ('collection', 'Collected'), ('delivery', 'Delivered')], default='dine-in', max_length=20)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled for later'), ('queued', 'Waiting to be started'), ('preparing', 'Being made'), ('ready', 'Ready at the pass'), ('served', 'Handed over'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('promised_at', models.DateTimeField(blank=True, null=True)),
                ('start_after', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='knight_restaurant.tablesession')),
            ],
            options={
                'db_table': 'knight_restaurant_ticket',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, default='', max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('actor', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='knight_restaurant.kitchenticket')),
            ],
            options={
                'db_table': 'knight_restaurant_ticket_event',
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order_item_id', models.BigIntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('prep_minutes', models.PositiveSmallIntegerField(default=0)),
                ('load_units', models.PositiveSmallIntegerField(default=0)),
                ('modifications', models.CharField(blank=True, default='', max_length=300)),
                ('state', models.CharField(choices=[('queued', 'Waiting'), ('preparing', 'Being made'), ('ready', 'Done'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='knight_restaurant.station')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='knight_restaurant.kitchenticket')),
            ],
            options={
                'db_table': 'knight_restaurant_ticket_line',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('expired', 'Expired')], default='held', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='knight_restaurant.capacityslot')),
            ],
            options={
                'db_table': 'knight_restaurant_slot_booking',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['slot', 'state'], name='knight_rest_booking_slot'), models.Index(fields=['state', 'expires_at'], name='knight_rest_booking_expiry'), models.Index(fields=['reference'], name='knight_rest_booking_ref')],
                'constraints': [models.UniqueConstraint(fields=('slot', 'reference'), name='knight_rest_one_booking_per_reference'), models.CheckConstraint(condition=models.Q(('units__gt', 0)), name='knight_rest_booking_is_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['location', 'is_active'], name='knight_rest_table_active'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('seats__gt', 0)), name='knight_rest_table_has_seats'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['table', 'closed_at'], name='knight_rest_session_open'),
        ),
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('table',), name='knight_rest_one_open_session_per_table'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['location', 'state', 'created_at'], name='knight_rest_ticket_board'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['state', 'promised_at'], name='knight_rest_ticket_due'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['-number'], name='knight_rest_ticket_number'),
        ),
        migrations.AddConstraint(
            model_name='kitchenticket',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['served', 'cancelled']), _negated=True), fields=('number',), name='knight_rest_one_live_ticket_per_number'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['ticket', 'occurred_at'], name='knight_rest_event_ticket'),
        ),
        migrations.AddIndex(
            model_name='ticketline',
            index=models.Index(fields=['station', 'state'], name='knight_rest_line_station'),
        ),
        migrations.AddConstraint(
            model_name='ticketline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='knight_rest_line_has_quantity'),
        ),
    ]
