"""
Parity tests for the ported catalogue.

These are not a line-by-line comparison with the .NET suites — the shapes differ
deliberately ([`adr/0023`](../../../../../docs/adr/0023-a-ported-store-is-single-tenant.md)).
They compare *behaviour*: the same slug rules, the same invariants, the same
refusals, so a catalogue that worked before works now.
"""

from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.test import TestCase

from apps.catalog.models import (
    Category,
    Modifier,
    ModifierGroup,
    Product,
    ProductMedia,
    ProductStatus,
    ProductVariant,
)
from apps.catalog.slugs import normalize


class SlugTests(TestCase):
    """
    The slug rules, unchanged from the .NET normaliser.

    Unchanged deliberately: existing catalogues have slugs generated by it, and
    a port that normalised differently would make previously distinct products
    collide or previously identical ones diverge.
    """

    def test_lowercases_and_hyphenates(self):
        self.assertEqual(normalize("Cheese Burger"), "cheese-burger")

    def test_collapses_runs_of_separators(self):
        self.assertEqual(normalize("Cheese   ---  Burger"), "cheese-burger")

    def test_trims_leading_and_trailing_separators(self):
        self.assertEqual(normalize("  !!Burger!!  "), "burger")

    def test_drops_non_ascii(self):
        # Persian names are common here, and a slug made only of them has no
        # ASCII left. That must be refused rather than silently become empty and
        # collide with every other such product.
        with self.assertRaises(ValidationError):
            normalize("برگر")

    def test_keeps_digits(self):
        self.assertEqual(normalize("Pizza 12 inch"), "pizza-12-inch")

    def test_refuses_blank(self):
        with self.assertRaises(ValidationError):
            normalize("   ")

    def test_truncates_without_leaving_a_trailing_hyphen(self):
        slug = normalize("a" * 149 + " b")

        self.assertLessEqual(len(slug), 150)
        self.assertFalse(slug.endswith("-"))


class ProductTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Burgers", slug="burgers")

    def _product(self, **overrides) -> Product:
        fields = {
            "category": self.category,
            "name": "Cheese Burger",
            "slug": "cheese-burger",
            "base_price": Decimal("120000"),
            "status": ProductStatus.ACTIVE,
        }
        fields.update(overrides)

        return Product.objects.create(**fields)

    def test_slug_is_normalized_on_save(self):
        product = self._product(slug="Cheese Burger!!")

        self.assertEqual(product.slug, "cheese-burger")

    def test_slug_is_unique_across_the_store(self):
        # The .NET constraint was (tenant, slug); this store is the tenant, so
        # the slug alone is the constraint.
        self._product()

        with self.assertRaises(IntegrityError), transaction.atomic():
            self._product(name="Another")

    def test_a_draft_product_is_not_orderable(self):
        product = self._product(status=ProductStatus.DRAFT)

        self.assertFalse(product.is_orderable)

    def test_an_unavailable_product_is_not_orderable(self):
        product = self._product(is_available=False)

        self.assertFalse(product.is_orderable)

    def test_an_invisible_product_is_not_orderable(self):
        product = self._product(is_visible=False)

        self.assertFalse(product.is_orderable)

    def test_archiving_hides_and_withdraws_without_deleting(self):
        # Orders keep naming the product, so the row has to survive; and a
        # withdrawn product left on the menu would be a shopper's
        # disappointment rather than a merchant's decision.
        product = self._product()
        product.archive()
        product.save()

        product.refresh_from_db()

        self.assertEqual(product.status, ProductStatus.ARCHIVED)
        self.assertFalse(product.is_visible)
        self.assertFalse(product.is_orderable)
        self.assertTrue(Product.objects.filter(pk=product.pk).exists())

    def test_a_category_with_products_cannot_be_deleted(self):
        self._product()

        with self.assertRaises(Exception):
            self.category.delete()


class VariantTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Burgers", slug="burgers")
        self.product = Product.objects.create(
            category=self.category, name="Burger", slug="burger", base_price=Decimal("100")
        )

    def test_sku_is_matched_case_and_space_insensitively(self):
        variant = ProductVariant.objects.create(
            product=self.product, name="Large", sku="  abc-1 ", price=Decimal("100")
        )

        self.assertEqual(variant.normalized_sku, "ABC-1")

    def test_a_sku_cannot_be_reused(self):
        ProductVariant.objects.create(
            product=self.product, name="Large", sku="ABC-1", price=Decimal("100")
        )

        with self.assertRaises(IntegrityError), transaction.atomic():
            ProductVariant.objects.create(
                product=self.product, name="Small", sku="abc-1", price=Decimal("80")
            )

    def test_variants_without_a_sku_do_not_collide(self):
        # The constraint is partial for exactly this reason: most variants have
        # no SKU, and a naive unique index would allow only one of them.
        ProductVariant.objects.create(product=self.product, name="Large", price=Decimal("100"))
        ProductVariant.objects.create(product=self.product, name="Small", price=Decimal("80"))

        self.assertEqual(self.product.variants.count(), 2)

    def test_only_one_variant_can_be_the_default(self):
        ProductVariant.objects.create(
            product=self.product, name="Large", price=Decimal("100"), is_default=True
        )

        with self.assertRaises(IntegrityError), transaction.atomic():
            ProductVariant.objects.create(
                product=self.product, name="Small", price=Decimal("80"), is_default=True
            )

    def test_a_compare_at_price_below_the_price_is_refused(self):
        variant = ProductVariant(
            product=self.product,
            name="Large",
            price=Decimal("100"),
            compare_at_price=Decimal("90"),
        )

        with self.assertRaises(ValidationError):
            variant.full_clean()


class ModifierGroupTests(TestCase):
    def test_max_below_min_is_refused(self):
        group = ModifierGroup(name="Size", min_selections=2, max_selections=1)

        with self.assertRaises(ValidationError):
            group.full_clean()

    def test_a_required_group_must_ask_for_at_least_one(self):
        # Otherwise "required" is a label with no effect, and the contradiction
        # surfaces as an order that validated and should not have.
        group = ModifierGroup(name="Size", is_required=True, min_selections=0, max_selections=2)

        with self.assertRaises(ValidationError):
            group.full_clean()

    def test_a_modifier_may_reduce_the_price(self):
        # Removing an ingredient is a discount. A field that could not express
        # one would force merchants to model it as a separate product.
        group = ModifierGroup.objects.create(name="Extras", max_selections=3)
        modifier = Modifier.objects.create(
            group=group, name="No cheese", price_delta=Decimal("-5000")
        )

        self.assertEqual(modifier.price_delta, Decimal("-5000"))


class MediaTests(TestCase):
    def setUp(self):
        category = Category.objects.create(name="Burgers", slug="burgers")
        self.product = Product.objects.create(
            category=category, name="Burger", slug="burger", base_price=Decimal("100")
        )

    def test_only_one_image_can_be_primary(self):
        ProductMedia.objects.create(product=self.product, storage_key="a.jpg", is_primary=True)

        with self.assertRaises(IntegrityError), transaction.atomic():
            ProductMedia.objects.create(product=self.product, storage_key="b.jpg", is_primary=True)
