# Generated by Django 5.1.15 on 2026-08-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
