# Generated by Django 5.1.15 on 2026-08-25 07:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('page', 'Page')], default='product', max_length=32)),
                ('object_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knight_search_document',
                'ordering': ('title',),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='knight_search_vector_gin'), models.Index(fields=['object_type', 'is_available'], name='knight_search_type_avail')],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id'), name='knight_search_one_document_per_object')],
            },
        ),
    ]
