# Generated by Django 5.1.15 on 2026-08-26 06:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('points_per_currency_unit', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency_per_point', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expiry_months', models.PositiveSmallIntegerField(default=12)),
                ('minimum_redemption_points', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knight_loyalty_programme',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('threshold_points', models.PositiveIntegerField(default=0)),
                ('earn_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('benefits', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'db_table': 'knight_loyalty_tier',
                'ordering': ('threshold_points', 'id'),
                'constraints': [models.UniqueConstraint(fields=('threshold_points',), name='knight_loyalty_one_tier_per_threshold')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('lifetime_points', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knight_loyalty.tier')),
            ],
            options={
                'db_table': 'knight_loyalty_account',
                'ordering': ('-lifetime_points', 'subject'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Earn', 'Earned'), ('Redeem', 'Redeemed'), ('Expire', 'Expired'), ('Adjust', 'Adjusted by staff')], max_length=16)),
                ('points', models.IntegerField()),
                ('points_remaining', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_order_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='knight_loyalty.account')),
            ],
            options={
                'db_table': 'knight_loyalty_transaction',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['account', 'kind', 'expires_at'], name='knight_loyalty_lot_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_order_id__isnull', False)), fields=('account', 'kind', 'source_order_id'), name='knight_loyalty_once_per_order_and_kind'), models.CheckConstraint(condition=models.Q(('points', 0), _negated=True), name='knight_loyalty_no_zero_movements')],
            },
        ),
    ]
