# Generated by Django 5.1.15 on 2026-08-28 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.UUIDField(unique=True)),
                ('slug', models.SlugField(max_length=120)),
                ('base_url', models.URLField(blank=True, default='')),
                ('secret', models.CharField(max_length=200)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('secrets', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knight_store',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='SeenNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=100)),
                ('seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='knightlink.store')),
            ],
            options={
                'db_table': 'knight_seen_nonce',
                'constraints': [models.UniqueConstraint(fields=('store', 'nonce'), name='knight_nonce_once')],
            },
        ),
    ]
