# Generated by Django 5.1.15 on 2026-08-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('normalized_phone', models.CharField(editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_name',),
                'indexes': [models.Index(fields=['status'], name='shoppers_sh_status_b567a8_idx')],
            },
        ),
    ]
