# Generated by Django 5.1.15 on 2026-08-28 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_slug', models.CharField(db_index=True, max_length=100)),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('payload', models.JSONField(default=dict)),
                ('guarantee', models.CharField(default='at-least-once', max_length=20)),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('DeadLettered', 'Dead-lettered')], default='Pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knight_webhook_delivery',
                'ordering': ('next_attempt_at', 'id'),
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='knight_delivery_due')],
            },
        ),
    ]
