# Generated by Django 5.1.15 on 2026-08-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knight_drill_record',
                'ordering': ('reference',),
            },
        ),
    ]
