<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Knight.Domain\Knight.Domain.csproj" />
    <ProjectReference Include="..\..\src\Knight.Application\Knight.Application.csproj" />
    <ProjectReference Include="..\..\src\Knight.Contracts\Knight.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Knight.UnitTests" />
    <InternalsVisibleTo Include="Knight.ArchitectureTests" />
    <InternalsVisibleTo Include="Knight.IntegrationTests" />
    <InternalsVisibleTo Include="Knight.Infrastructure" />
  </ItemGroup>

</Project>
