#!/usr/bin/env python3
"""
Scaffold a KNIGHT external-service Feature.

Turns a catalogue slug into a complete, secure, deployable external_service
Feature — manifest, a service built on `knight_service_kit`, Dockerfile and a
compose file — in one command. The generated service already verifies KNIGHT's
control calls and each store's per-store secret, records every event the store
publishes and serves a dashboard; a Feature that needs more than counting fills
in its own logic on top, but it installs and runs from the moment it is scaffolded.

    python scaffold_external_service.py \
        --slug loyalty-rewards --name "Loyalty and Rewards" \
        --subdomain loyalty.bojanstore.com --port 8091

Writes features/knight-feature-<slug>-service/. Business logic beyond event
recording is not invented — that is the one thing a generator cannot do.
"""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

EVENTS = [
    "order.placed", "order.paid", "order.cancelled", "order.refunded", "order.fulfilled",
    "cart.abandoned", "customer.registered", "customer.updated",
    "product.created", "product.updated", "product.stock_changed",
]


def prefix_of(slug: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", slug.upper()).strip("_")


def manifest(slug: str, name: str, subdomain: str, version: str, events: list[str]) -> str:
    prefix = prefix_of(slug)
    hooks = "\n".join(
        f"  - event: {e}\n    path: /hooks/{e.replace('.', '-').replace('_', '-')}\n    delivery: at-least-once"
        for e in events
    )
    return f"""# {name}, delivered as an external service (architecture: external_service).
# Generated by scaffold_external_service.py: a store forwards its events and
# proxies the merchant's screen here, so a store of any runtime can use it. The
# service runs once, at the base_url below, and proves who it is with the shared
# secret KNIGHT issues (adr/0033, adr/0034).
apiVersion: knight.dev/v1
slug: {slug}
version: {version}
name: {name}
description: >-
  {name} run as a service rather than installed into the store: the store
  forwards its lifecycle events and proxies the merchant's screen through, so a
  store of any runtime can use it.

architecture: external_service

service:
  base_url: https://{subdomain}
  auth: hmac-sha256
  health: /healthz
  # The store-side secret's NAME; KNIGHT issues and delivers the value. The
  # service verifies KNIGHT's control calls with {prefix}_CONTROL_SECRET instead,
  # set out of band on both sides.
  secret: {prefix}_SERVICE_SECRET

webhooks:
{hooks}

api_proxies:
  - prefix: admin/{slug}/
    upstream: /api/v1/admin/
    methods: [GET]
    identity: staff

ui_mounts:
  - slot: admin.sidebar
    label: {name}
    path: /admin/{slug}
    kind: iframe

configuration:
  defaults:
    retention_days: 90
"""


APP_PY = '''"""Generated service for {name}. Security, event recording and the dashboard come
from knight_service_kit; declare only what is specific to this Feature here."""

from knight_service_kit import create_app, DEFAULT_EVENTS

app = create_app("{name}", DEFAULT_EVENTS, env_prefix="{prefix}", version="{version}")
'''

REQUIREMENTS = "fastapi==0.115.6\nuvicorn[standard]==0.34.0\n"

DOCKERFILE = '''FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY knight_service_kit.py app.py ./
RUN useradd --uid 65532 --create-home --shell /usr/sbin/nologin svc \\
 && mkdir -p /data && chown -R svc:svc /data
USER svc
EXPOSE {port}
VOLUME ["/data"]
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "{port}"]
'''

COMPOSE = '''# Generated. Runs {name} behind the host's nginx (TLS for {subdomain}).
name: {container}
services:
  service:
    build: ../service
    container_name: {container}
    restart: unless-stopped
    environment:
      {prefix}_CONTROL_SECRET: ${{{prefix}_CONTROL_SECRET}}
      {prefix}_DB_PATH: /data/service.db
    volumes:
      - service-data:/data
    ports:
      - "127.0.0.1:{port}:{port}"
volumes:
  service-data:
'''


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold a KNIGHT external-service Feature.")
    ap.add_argument("--slug", required=True, help="Catalogue slug the store is entitled to, e.g. loyalty-rewards")
    ap.add_argument("--name", required=True, help='Display name, e.g. "Loyalty and Rewards"')
    ap.add_argument("--subdomain", required=True, help="Public host for the service, e.g. loyalty.bojanstore.com")
    ap.add_argument("--port", type=int, required=True, help="Container port, e.g. 8091")
    ap.add_argument("--version", default="2.0.0")
    ap.add_argument("--events", default="", help="Comma-separated event names; defaults to the full catalogue")
    ap.add_argument("--features-dir", type=Path, default=Path(__file__).resolve().parents[1])
    args = ap.parse_args()

    events = [e.strip() for e in args.events.split(",") if e.strip()] or EVENTS
    prefix = prefix_of(args.slug)
    container = f"bojan-{args.slug}"
    root = args.features_dir / f"knight-feature-{args.slug}-service"
    (root / "service").mkdir(parents=True, exist_ok=True)
    (root / "deploy").mkdir(parents=True, exist_ok=True)

    (root / "knight_manifest.yaml").write_text(
        manifest(args.slug, args.name, args.subdomain, args.version, events), encoding="utf-8"
    )
    (root / "service" / "app.py").write_text(
        APP_PY.format(name=args.name, prefix=prefix, version=args.version), encoding="utf-8"
    )
    (root / "service" / "requirements.txt").write_text(REQUIREMENTS, encoding="utf-8")
    (root / "service" / "Dockerfile").write_text(DOCKERFILE.format(port=args.port), encoding="utf-8")
    (root / "deploy" / "docker-compose.yml").write_text(
        COMPOSE.format(name=args.name, subdomain=args.subdomain, container=container, prefix=prefix, port=args.port),
        encoding="utf-8",
    )
    # The image is self-contained: ship the kit inside each service.
    shutil.copy2(Path(__file__).with_name("knight_service_kit.py"), root / "service" / "knight_service_kit.py")

    print(f"Scaffolded {root}")
    print(f"  slug={args.slug} prefix={prefix} port={args.port} base_url=https://{args.subdomain}")
    print("Next: commit it, then run deliver_service.sh to publish, deploy and install.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
