using System.Text.Json;
using FeatureDelivery.Domain;
using Knight.Application.Abstractions.ControlPlane;
using Knight.Application.Abstractions.Security;
using Knight.Application.Exceptions;
using Microsoft.Extensions.Logging;

namespace FeatureDelivery;

/// <summary>
/// The secret a store signs a Feature's service with: issued here, rotated here,
/// revoked here.
///
/// Until this existed, that secret was an environment variable an operator typed
/// into two places. Correct for one store, an incident at ten: nobody could
/// rotate it without an outage, nobody could say when it was issued, and
/// withdrawing an entitlement stopped the store forwarding without stopping the
/// service answering (<c>docs/adr/0034-a-shared-secret-has-a-lifetime.md</c>).
///
/// **The order is the design.** The service is told first and the store second.
/// A store that held a credential the service had not heard of would be a store
/// signing with something that cannot verify, and that window is an outage — so
/// if the service call fails, nothing is delivered and the store keeps working
/// with what it has.
///
/// The store's half travels down the ordinary configuration-secret path. Nothing
/// new reaches the store, and nothing here knows how a store applies a
/// configuration: it sets a secret and queues the job the delivery engine
/// already had.
/// </summary>
internal sealed class ServiceCredentialService : IServiceCredentialService
{
    /// <summary>
    /// How long the previous secret keeps working when nobody says.
    ///
    /// An hour, and the number is chosen from the failure it prevents: the store
    /// only stops using the old secret once it has taken delivery of a new
    /// configuration, and taking delivery is a queued job an agent polls for. A
    /// window shorter than the polling interval would cut off a store that is
    /// doing exactly what it was told to.
    /// </summary>
    public const int DefaultOverlapSeconds = 3600;

    /// <summary>
    /// The ceiling. A week from a typo would leave a replaced secret valid for a
    /// week, and this is the one number where a mistake is silent.
    /// </summary>
    public const int MaximumOverlapSeconds = 24 * 3600;

    private readonly IFeatureInstallationRepository _installations;
    private readonly IFeatureConfigurationRepository _configurations;
    private readonly IFeatureDeliveryService _delivery;
    private readonly IServiceEndpointReader _endpoints;
    private readonly IServiceControlPlane _controlPlane;
    private readonly ISecureTokenFactory _tokens;
    private readonly ISecretProtector _secrets;
    private readonly IAuditTrail _audit;
    private readonly ILogger<ServiceCredentialService> _logger;

    public ServiceCredentialService(
        IFeatureInstallationRepository installations,
        IFeatureConfigurationRepository configurations,
        IFeatureDeliveryService delivery,
        IServiceEndpointReader endpoints,
        IServiceControlPlane controlPlane,
        ISecureTokenFactory tokens,
        ISecretProtector secrets,
        IAuditTrail audit,
        ILogger<ServiceCredentialService> logger)
    {
        _installations = installations;
        _configurations = configurations;
        _delivery = delivery;
        _endpoints = endpoints;
        _controlPlane = controlPlane;
        _tokens = tokens;
        _secrets = secrets;
        _audit = audit;
        _logger = logger;
    }

    public async Task<ServiceCredentialResult> IssueAsync(
        Guid storeId,
        Guid featureId,
        int? overlapSeconds,
        CancellationToken cancellationToken)
    {
        var endpoint = await RequireEndpointAsync(storeId, featureId, cancellationToken);
        var existing = await _configurations.FindAsync(storeId, featureId, cancellationToken);
        var secrets = await ReadSecretsAsync(existing);

        var rotating = secrets.ContainsKey(endpoint.SecretName);
        var overlap = Clamp(overlapSeconds);

        // Random, opaque, and generated by the same factory that mints store
        // client secrets. The raw value exists here and in two places
        // afterwards — the service and the store — and nowhere else.
        var secret = _tokens.Generate().RawValue;

        // The service first. Always. A failure here throws, nothing is
        // delivered, and the store carries on with the secret it already has.
        if (rotating)
        {
            await _controlPlane.RotateAsync(endpoint, secret, overlap, cancellationToken);
        }
        else
        {
            await _controlPlane.RegisterAsync(endpoint, secret, cancellationToken);
        }

        secrets[endpoint.SecretName] = secret;

        // And the store second, down the path every other configuration secret
        // already travels. This queues the job; the store applies it when its
        // agent next polls, and until it does, the old secret is still inside
        // its overlap window.
        await _delivery.ConfigureAsync(
            storeId,
            featureId,
            existing?.ValuesJson ?? "{}",
            secrets,
            cancellationToken);

        var configuration = await _configurations.FindAsync(storeId, featureId, cancellationToken);

        await _audit.RecordAsync(
            rotating ? "feature.service_secret.rotated" : "feature.service_secret.issued",
            "FeatureConfiguration",
            $"{storeId}:{endpoint.FeatureSlug}",
            await CustomerOfAsync(storeId, featureId, cancellationToken),
            cancellationToken,
            // The name, the window and the version. Never the value: an audit
            // trail that recorded secrets would be the easiest place in the
            // system to read one out of.
            newValue: new
            {
                endpoint.FeatureSlug,
                endpoint.SecretName,
                OverlapSeconds = rotating ? overlap : 0,
                Version = configuration?.Version ?? 0,
            });

        _logger.LogInformation(
            "{Action} the service secret for store {StoreId} and feature {Feature}.",
            rotating ? "Rotated" : "Issued",
            storeId,
            endpoint.FeatureSlug);

        return new ServiceCredentialResult(
            storeId,
            endpoint.FeatureSlug,
            endpoint.SecretName,
            rotating,
            rotating ? overlap : 0,
            configuration?.Version ?? 0);
    }

    public async Task<ServiceCredentialResult> RevokeAsync(
        Guid storeId,
        Guid featureId,
        CancellationToken cancellationToken)
    {
        var endpoint = await RequireEndpointAsync(storeId, featureId, cancellationToken);

        // The service first here too, and for a stronger reason: this is the
        // half a store cannot be trusted with. Removing the secret from the
        // store's configuration alone would leave a store with a stale registry
        // — or one restored from a backup — still able to call a Feature nobody
        // pays for.
        await _controlPlane.RevokeAsync(endpoint, cancellationToken);

        var existing = await _configurations.FindAsync(storeId, featureId, cancellationToken);
        var secrets = await ReadSecretsAsync(existing);
        var version = existing?.Version ?? 0;

        if (secrets.Remove(endpoint.SecretName))
        {
            await _delivery.ConfigureAsync(
                storeId,
                featureId,
                existing?.ValuesJson ?? "{}",
                secrets,
                cancellationToken);

            version = (await _configurations.FindAsync(storeId, featureId, cancellationToken))?.Version ?? version;
        }

        await _audit.RecordAsync(
            "feature.service_secret.revoked",
            "FeatureConfiguration",
            $"{storeId}:{endpoint.FeatureSlug}",
            await CustomerOfAsync(storeId, featureId, cancellationToken),
            cancellationToken,
            newValue: new { endpoint.FeatureSlug, endpoint.SecretName, Version = version });

        _logger.LogInformation(
            "Revoked store {StoreId}'s credential with {Feature}.", storeId, endpoint.FeatureSlug);

        return new ServiceCredentialResult(storeId, endpoint.FeatureSlug, endpoint.SecretName, false, 0, version);
    }

    public async Task<IReadOnlyCollection<ServiceCredentialResult>> RevokeForCustomerAsync(
        Guid customerId,
        Guid featureId,
        CancellationToken cancellationToken)
    {
        var installations = await _installations.ListForCustomerFeatureAsync(customerId, featureId, cancellationToken);
        var revoked = new List<ServiceCredentialResult>();

        foreach (var installation in installations)
        {
            // Only the ones that are actually a service. A customer's
            // entitlement covers stores that may have this Feature installed
            // either way, and an entitlement change must not fail because one of
            // them runs the in-process build.
            if (await _endpoints.ForInstallationAsync(installation.StoreId, featureId, cancellationToken) is null)
            {
                continue;
            }

            revoked.Add(await RevokeAsync(installation.StoreId, featureId, cancellationToken));
        }

        return revoked;
    }

    private async Task<ServiceEndpointDescriptor> RequireEndpointAsync(
        Guid storeId,
        Guid featureId,
        CancellationToken cancellationToken)
    {
        var endpoint = await _endpoints.ForInstallationAsync(storeId, featureId, cancellationToken);

        if (endpoint is null)
        {
            // Refused rather than ignored. An in-process Feature has no service
            // to register with, and issuing it a credential would put a secret
            // in a store's configuration that nothing will ever check.
            throw new ConflictException(
                "That Feature is not installed on this store as a service, so it has no shared secret.");
        }

        return endpoint;
    }

    private Task<Dictionary<string, string>> ReadSecretsAsync(FeatureConfiguration? configuration)
    {
        if (configuration?.EncryptedSecretsJson is null)
        {
            return Task.FromResult(new Dictionary<string, string>(StringComparer.Ordinal));
        }

        // Read back and rewritten whole, because the store holds one sealed
        // document. A Feature's other secrets — a payment provider key — must
        // survive its shared secret being rotated.
        var secrets = JsonSerializer.Deserialize<Dictionary<string, string>>(
            _secrets.Unprotect(configuration.EncryptedSecretsJson));

        return Task.FromResult(secrets ?? new Dictionary<string, string>(StringComparer.Ordinal));
    }

    private async Task<Guid> CustomerOfAsync(Guid storeId, Guid featureId, CancellationToken cancellationToken)
    {
        var installation = await _installations.FindAsync(storeId, featureId, cancellationToken);

        return installation?.CustomerId ?? Guid.Empty;
    }

    private static int Clamp(int? asked) =>
        asked is null ? DefaultOverlapSeconds : Math.Clamp(asked.Value, 0, MaximumOverlapSeconds);
}
