# Generated by Django 5.1.15 on 2026-08-27 11:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Everything this Feature owns.

    One constraint below is the Feature rather than decoration.
    `knight_sub_one_period_per_sequence` is what stops a shopper being charged
    twice for one month: a period is opened before it is charged, numbered per
    subscription, and unique on that number - so a cron that fires twice, a
    webhook delivered twice and an operator running the worker by hand during an
    incident all end at the same index, and exactly one of them opens the period.

    No extension, and no `CREATE EXTENSION`: nothing here is matched fuzzily
    (docs/adr/0031-database-extensions-are-declared-not-migrated.md).
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('source_shopper_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('state', models.CharField(choices=[('pending', 'Not started yet'), ('active', 'Billing normally'), ('past-due', 'A payment failed and will be retried'), ('unpaid', 'Retries are exhausted'), ('paused', 'Paused by the shopper or the merchant'), ('cancelled', 'Ended by somebody'), ('ended', 'Ran to its natural end')], default='pending', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('interval', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Every week'), ('monthly', 'Every month'), ('yearly', 'Every year')], default='monthly', max_length=12)),
                ('interval_count', models.PositiveSmallIntegerField(default=1)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('provider', models.CharField(default='manual', max_length=40)),
                ('payment_method_reference', models.CharField(blank=True, default='', max_length=200)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_period', models.PositiveIntegerField(default=0)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('periods_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=500)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'knight_subscriptions_subscription',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['state', 'next_run_at'], name='knight_sub_due'), models.Index(fields=['source_shopper_id'], name='knight_sub_shopper')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0'))), name='knight_sub_amount_not_negative'), models.CheckConstraint(condition=models.Q(('interval_count__gt', 0)), name='knight_sub_interval_count_is_positive')],
            },
        ),
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('state', models.CharField(choices=[('pending', 'Not charged yet'), ('paid', 'Charged successfully'), ('failed', 'The charge failed'), ('skipped', 'Deliberately not charged'), ('refunded', 'Charged and given back')], default='pending', max_length=12)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='knight_subscriptions.subscription')),
            ],
            options={
                'db_table': 'knight_subscriptions_period',
                'ordering': ('subscription', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, default='', max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('actor', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='knight_subscriptions.subscription')),
            ],
            options={
                'db_table': 'knight_subscriptions_event',
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_id', models.BigIntegerField(blank=True, null=True)),
                ('source_variant_id', models.BigIntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='knight_subscriptions.subscription')),
            ],
            options={
                'db_table': 'knight_subscriptions_line',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order_number', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='knight_subscriptions.billingperiod')),
            ],
            options={
                'db_table': 'knight_subscriptions_order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BillingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('outcome', models.CharField(choices=[('succeeded', 'The money moved'), ('failed', 'The provider declined it'), ('refused', 'This Feature would not try')], max_length=12)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='knight_subscriptions.billingperiod')),
            ],
            options={
                'db_table': 'knight_subscriptions_attempt',
                'ordering': ('occurred_at', 'id'),
                'indexes': [models.Index(fields=['period', 'occurred_at'], name='knight_sub_attempt_period'), models.Index(fields=['outcome'], name='knight_sub_attempt_outcome')],
            },
        ),
        migrations.AddIndex(
            model_name='billingperiod',
            index=models.Index(fields=['state', 'retry_at'], name='knight_sub_period_retry'),
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=('subscription', 'sequence'), name='knight_sub_one_period_per_sequence'),
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='knight_sub_period_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['subscription', 'occurred_at'], name='knight_sub_event'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='knight_sub_line_has_quantity'),
        ),
    ]
