# Generated by Django 5.1.15 on 2026-08-25 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(db_index=True)),
                ('shopper_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='', max_length=4000)),
                ('status', models.CharField(choices=[('Pending', 'Awaiting moderation'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Pending', max_length=16)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('source_order_id', models.BigIntegerField(blank=True, null=True)),
                ('moderator_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knight_review',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['product_id', 'status'], name='knight_review_prod_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('shopper_id__isnull', False)), fields=('product_id', 'shopper_id'), name='knight_review_once_per_shopper_and_product'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='knight_review_rating_between_one_and_five')],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('author_name', models.CharField(default='The store', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='knight_reviews.review')),
            ],
            options={
                'db_table': 'knight_review_reply',
            },
        ),
    ]
