# Generated by Django 5.1.15 on 2026-08-26 11:18

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Everything this Feature owns, and one statement it does not.

    The `CREATE EXTENSION` below is the same idempotent statement the store's
    `create-extensions` step runs before this migration, from the declaration in
    the manifest. It is repeated here for the paths with no installer in them:
    `manage.py migrate` on a developer's checkout, and Django's test database,
    which the test runner creates and migrates itself.

    Its reverse is a deliberate no-op. `pg_trgm` is shared with the store and
    with every other Feature in the same database — `advanced-search` uses it too
    — so dropping it on the way back out could break something this Feature has
    never heard of
    (docs/adr/0031-database-extensions-are-declared-not-migrated.md).
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS "pg_trgm"',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knight_inventory_supplier',
                'ordering': ('name',),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='knight_inv_supplier_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('object_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('unit', models.CharField(default='each', max_length=20)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_tracked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='knight_inventory.supplier')),
            ],
            options={
                'db_table': 'knight_inventory_item',
                'ordering': ('sku',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('partially-received', 'Partially received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='knight_inventory.supplier')),
            ],
            options={
                'db_table': 'knight_inventory_purchase_order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('kind', models.CharField(choices=[('low-stock', 'Low stock'), ('out-of-stock', 'Out of stock')], max_length=16)),
                ('available', models.DecimalField(decimal_places=3, max_digits=14)),
                ('threshold', models.DecimalField(decimal_places=3, max_digits=14)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='knight_inventory.stockitem')),
            ],
            options={
                'db_table': 'knight_inventory_alert',
                'ordering': ('-raised_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('item', 'location'), name='knight_inv_one_open_alert_per_item')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('held', 'Held'), ('committed', 'Committed'), ('released', 'Released'), ('expired', 'Expired')], default='held', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='knight_inventory.stockitem')),
            ],
            options={
                'db_table': 'knight_inventory_reservation',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['item', 'location', 'state'], name='knight_inv_res_item_state'), models.Index(fields=['state', 'expires_at'], name='knight_inv_res_expiry')],
                'constraints': [models.UniqueConstraint(fields=('item', 'reference'), name='knight_inv_one_reservation_per_reference'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='knight_inv_reservation_is_positive')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_received', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='knight_inventory.purchaseorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='knight_inventory.stockitem')),
            ],
            options={
                'db_table': 'knight_inventory_purchase_line',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('order', 'item'), name='knight_inv_one_line_per_item_per_order'), models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='knight_inv_po_line_is_positive')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('receipt', 'Received from a supplier'), ('sale', 'Sold to a customer'), ('return', 'Returned by a customer'), ('adjustment', 'Counted and corrected'), ('shrinkage', 'Lost, damaged or written off'), ('transfer-in', 'Moved in from another location'), ('transfer-out', 'Moved out to another location')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='knight_inventory.stockitem')),
            ],
            options={
                'db_table': 'knight_inventory_movement',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['item', 'location'], name='knight_inv_move_item_loc'), models.Index(fields=['reference'], name='knight_inv_move_reference'), models.Index(fields=['occurred_at'], name='knight_inv_move_occurred')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='knight_inv_movement_is_not_zero')],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['is_tracked'], name='knight_inv_item_tracked'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sku'], name='knight_inv_item_sku_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='knight_inv_item_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['state'], name='knight_inv_po_state'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'state'], name='knight_inv_po_supplier'),
        ),
    ]
