# Generated by Django 5.1.15 on 2026-08-20 05:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order_id', models.BigIntegerField(unique=True)),
                ('order_number', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('method', models.CharField(choices=[('Online', 'Online'), ('PayOnFulfillment', 'Pay on fulfilment')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='', max_length=20)),
                ('to_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment')),
            ],
            options={
                'verbose_name_plural': 'payment status history',
                'ordering': ('changed_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Processing', 'Processing'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Created', max_length=20)),
                ('provider_key', models.CharField(blank=True, default='', max_length=100)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=100)),
                ('failure_message', models.CharField(blank=True, default='', max_length=500)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
            options={
                'ordering': ('attempt_number',),
                'constraints': [models.UniqueConstraint(fields=('payment', 'attempt_number'), name='payments_attempt_number_unique')],
            },
        ),
    ]
