# Generated by Django 5.1.15 on 2026-08-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Everything this Feature owns, and — the point of the whole design — nothing
    that belongs to anybody else.

    Eight CreateModels, all of them in this app. There is no AlterField here, no
    RunPython over another Feature's rows and no column added to a table this
    package does not own, which is what the phrase "high migration risk and
    deliberately late" was about for seven phases. `advanced-inventory` and
    `restaurant-operations` each carried their `location` column from their own
    1.0, so there was never anything to reshape: this migration names codes that
    already exist, and its reverse leaves every stock movement and every kitchen
    ticket holding exactly the code it always held.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knight_locations_staff',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('shop', 'A place customers come to'), ('kitchen', 'A place food is made'), ('warehouse', 'A place stock is kept'), ('dark-store', 'A place that only fulfils, with no counter')], default='shop', max_length=20)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('address_line1', models.CharField(blank=True, default='', max_length=250)),
                ('address_line2', models.CharField(blank=True, default='', max_length=250)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knight_locations_location',
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active', 'kind'], name='knight_loc_active_kind')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='knight_loc_one_default')],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('postal-prefix', 'The delivery postcode starts with this'), ('city', 'The delivery city is this'), ('zone', 'The delivery zone is named this'), ('always', 'Anything not matched above')], max_length=20)),
                ('pattern', models.CharField(blank=True, default='', max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='knight_locations.location')),
            ],
            options={
                'db_table': 'knight_locations_rule',
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order_number', models.BigIntegerField(unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='knight_locations.location')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='knight_locations.routingrule')),
            ],
            options={
                'db_table': 'knight_locations_order_routing',
                'ordering': ('-decided_at',),
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=80)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='knight_locations.location')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='knight_locations.staffmember')),
            ],
            options={
                'db_table': 'knight_locations_assignment',
                'ordering': ('-starts_on',),
            },
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='knight_locations.location')),
            ],
            options={
                'db_table': 'knight_locations_closure',
                'ordering': ('starts_on',),
                'indexes': [models.Index(fields=['location', 'starts_on'], name='knight_loc_closure_when')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='knight_loc_closure_ends_after_it_starts')],
            },
        ),
        migrations.CreateModel(
            name='MenuAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('object_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='knight_locations.location')),
            ],
            options={
                'db_table': 'knight_locations_menu',
                'ordering': ('location', 'sku'),
                'constraints': [models.UniqueConstraint(fields=('location', 'sku'), name='knight_loc_one_menu_entry_per_sku')],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='knight_locations.location')),
            ],
            options={
                'db_table': 'knight_locations_hours',
                'ordering': ('weekday', 'opens'),
                'constraints': [models.UniqueConstraint(fields=('location', 'weekday', 'opens'), name='knight_loc_one_window_per_start'), models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='knight_loc_weekday_is_a_weekday'), models.CheckConstraint(condition=models.Q(('closes__gt', models.F('opens'))), name='knight_loc_window_ends_after_it_starts')],
            },
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['is_active', 'priority'], name='knight_loc_rule_order'),
        ),
        migrations.AddConstraint(
            model_name='routingrule',
            constraint=models.UniqueConstraint(fields=('kind', 'pattern'), name='knight_loc_one_rule_per_pattern'),
        ),
        migrations.AddIndex(
            model_name='orderrouting',
            index=models.Index(fields=['location', 'decided_at'], name='knight_loc_routed_orders'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['location', 'ends_on'], name='knight_loc_roster'),
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('staff', 'location'), name='knight_loc_one_open_assignment'),
        ),
    ]
