# Generated by Django 5.1.15 on 2026-08-26 06:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('Issue', 'Issued'), ('Redeem', 'Redeemed'), ('Refund', 'Refunded'), ('Void', 'Voided')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('source_order_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'knight_store_credit_entry',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['subject', 'created_at'], name='knight_credit_subject_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_order_id__isnull', False)), fields=('subject', 'kind', 'source_order_id'), name='knight_credit_once_per_subject_order_and_kind'), models.CheckConstraint(condition=models.Q(('amount', Decimal('0')), _negated=True), name='knight_credit_no_zero_movements')],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('normalized_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Depleted', 'Fully redeemed'), ('Void', 'Voided')], default='Active', max_length=16)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sender_name', models.CharField(blank=True, default='', max_length=150)),
                ('message', models.TextField(blank=True, default='', max_length=1000)),
                ('source_order_id', models.BigIntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'db_table': 'knight_gift_card',
                'ordering': ('-issued_at', '-id'),
                'indexes': [models.Index(fields=['status', '-issued_at'], name='knight_gc_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Issue', 'Issued'), ('Redeem', 'Redeemed'), ('Refund', 'Refunded'), ('Void', 'Voided')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_order_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='knight_gift_cards.giftcard')),
            ],
            options={
                'db_table': 'knight_gift_card_entry',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['card', 'created_at'], name='knight_gc_entry_card_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_order_id__isnull', False)), fields=('card', 'kind', 'source_order_id'), name='knight_gc_once_per_card_order_and_kind'), models.CheckConstraint(condition=models.Q(('amount', Decimal('0')), _negated=True), name='knight_gc_no_zero_movements')],
            },
        ),
    ]
