# Generated by Django 5.1.15 on 2026-08-25 06:29

"""
Version 2.0.0: this Feature stops owning plain coupons and starts owning the
sophistication that is actually sold.

**This migration destroys data and cannot be reversed.** It drops the promotion,
coupon and redemption tables, whose rows belong to the base store now
(adr/0024). Run `manage.py knight_absorb_promotions` on the store BEFORE
upgrading to this version, or every campaign and every redemption count on that
store is gone - and a redemption count that is gone hands every used-up coupon
back to the next shopper who tries it.

The manifest declares `migrations.reversible: false` for exactly this reason. A
failed upgrade here stops with ManualInterventionRequired rather than pretending
Django's reverse can put a customer's campaigns back
(adr/0016).
"""

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knight_promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('stacks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ('-priority', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyXGetY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('stacks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_product_id', models.BigIntegerField()),
                ('trigger_quantity', models.PositiveIntegerField(default=1)),
                ('reward_product_id', models.BigIntegerField()),
                ('reward_quantity', models.PositiveIntegerField(default=1)),
                ('reward_percent', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('maximum_awards_per_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'buy X get Y campaigns',
                'ordering': ('-priority', 'id'),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='couponredemption',
            name='coupon',
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knight_promotions.bundle')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponRedemption',
        ),
        migrations.AddConstraint(
            model_name='bundleitem',
            constraint=models.UniqueConstraint(fields=('bundle', 'product_id'), name='advanced_promotions_bundle_product_once'),
        ),
    ]
