# Generated by Django 5.1.15 on 2026-08-26 09:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('monthly_token_cap', models.PositiveIntegerField(default=200000)),
                ('monthly_cost_cap', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('window_started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knight_ai_reports_budget',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Day', 'A day'), ('Week', 'A week')], default='Day', max_length=8)),
                ('covers', models.DateField()),
                ('state', models.CharField(choices=[('Computed', 'Findings computed, not narrated'), ('Narrated', 'Findings computed and narrated'), ('Refused', 'Narration refused: over budget or unavailable'), ('Failed', 'The run could not complete')], default='Computed', max_length=12)),
                ('narrative', models.TextField(blank=True, default='')),
                ('narration_note', models.CharField(blank=True, default='', max_length=250)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'knight_ai_report',
                'ordering': ('-covers', 'period'),
                'constraints': [models.UniqueConstraint(fields=('period', 'covers'), name='knight_ai_one_report_per_period')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('Info', 'Worth knowing'), ('Notable', 'Worth looking at'), ('Urgent', 'Worth acting on')], default='Info', max_length=10)),
                ('headline', models.CharField(max_length=300)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='knight_ai_reports.report')),
            ],
            options={
                'db_table': 'knight_ai_finding',
                'ordering': ('report', '-severity', 'code'),
            },
        ),
    ]
